index.html

initial index.htm, index.js, and linked style.css files

boilerplate done

---

README.md

Here we've added details on the user stories, user acceptance criteria, accessibility, testing and stretch goals.
Still need to add info on architecture.
relates to #2 relates to #3 relates to #4 relates to #5

Added outline and some detail to ReadMe

---

index.html

 Modified the HTML structure -  add two buttons

---

README.md

adding another stretch goal to alter difficulty of game

---

README.md

adding two stretch goals for difficulty level and filtering movies

---

js/index.js

add a fetch function that grabs API data when given a url
fix #23

add fetch function

---

index.html

add new javascript files for each of our APIs

---

js/giphy.js
tests/index.html
tests/tests.js

include QUnit in tests directory
relates to #27

 Add testing functionality

---

js/giphy.js
js/index.js
js/moviedb.js
tests/tests.js

still needs better testing and some refactoring
relates to #29

Giphy function with minimal testing

---

js/elementCreation.js
tests/index.html
tests/tests.js

Tests adding checking that function adds the right tags, the right number of tags, the right text and the right src.
Also adding tests checking that the url counting function (for counting gifs) is working.
relates to #38

adding tests to element creation code

---

README.md
js/giphy.js
js/index.js
package.json
tests/tests.js

fix #40 
fix #34 
fix #41 
fix #9 
fix #37

Giphy function

---

css/style.css
js/elementCreation.js
tests/tests.js

Still need to integrate this with API data

Columns, text and images now append to DOM

---

index.html
tests/tests.js

build framework that connects the different modules throughout our app

---

css/style.css
index.html
js/app.js

relates to #47 
The Form loads after the gifs have been loaded and validates user input once they submit the form.

added basic form validation

---

js/app.js
js/elementCreation.js
js/index.js

hooks in the display of gifs to the app.js script
relates to #45

app function  connects to dom

---

js/app.js
js/elementCreation.js
js/form.js
js/giphy.js
js/index.js
js/moviedb.js

added comments to the code

---

index.html
js/app.js
js/elementCreation.js

add reset button

---

css/style.css
index.html

Added background colour, made buttons larger, centralised elements and improved appearance of input field
relates to #53

added basic styling

---

css/style.css
index.html
js/app.js
js/form.js
js/giphy.js

Add game validation to DOM

---

index.html

Now at the top of the page
relates to #53

moving the reset button as it was confusing

---

test.js

deleted extra testjs file

---

package.json

A name and description has been added - previously was 'stopwatch'.
fixes #70

adding the correct name and description in the package.json file

---

css/style.css
index.html

Gifs now display full width, as does the input on mobile and ipad. The input text size is also altered to ensure it is all visible.
relates to #54

Mobile optimisation

---

js/app.js

When clicked, reset also clears input. Focus remains on input
fixes #71

Reset button now clears input and puts focus back on input

---

css/style.css
tests/index.html

Oops.. Avenir is also a paid font and not available on linux. Now using Roboto as a google font.
fixes #86 (again)

changing font to google font roboto

---

css/style.css
index.html
js/form.js

 Add modal pop up for in game messages

---

css/style.css
js/form.js

green for correct answer + the answer, red for try again.
relates #53 and #82

 add different colors to the modal pop out
